language: haskell

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install alt-ergo
    - cabal install --only-dependencies

install:
    - cabal install

script:
    - ./run_tests.sh
