language: haskell

install:
    - git submodule update --init
    - git clone https://github.com/nick8325/quickspec
    - cabal update
    - (cd quickspec; cabal install)
    - cabal install

script:
    - cabal test
