language: haskell

ghc:
    - 7.8

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - cabal update
    - cabal install alex happy
    - which alex
    - which happy
    - alex --version
    - happy --version
    - echo "deb http://cvc4.cs.nyu.edu/debian/ unstable/" | sudo tee -a /etc/apt/sources.list
    - echo "deb-src http://cvc4.cs.nyu.edu/debian/ unstable/" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get install cvc4 --force-yes
    - sudo apt-get install alt-ergo spass
    - git clone https://github.com/nick8325/quickcheck.git
    - git clone https://github.com/nick8325/quickspec.git --branch v2
    - (cd quickspec; git checkout f9581c269c2b1cd6cb7288bf7ee74b09650108d3)
    - cabal install quickspec/ quickcheck/ . --only-dependencies -f-z3
    - cabal install quickspec/ quickcheck/ -f-z3

install:
    - cabal install

script:
    - ./run_tests.sh
