language: haskell

ghc:
    - 7.4
    - 7.6
    - 7.8

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install alt-ergo
    - git clone https://github.com/nick8325/quickcheck.git
    - git clone https://github.com/nick8325/quickspec.git
    - cabal install quickspec/ quickcheck/ . --only-dependencies
    - cabal install quickspec/ quickcheck/

install:
    - cabal install

script:
    - ./run_tests.sh
